import type { CompositeTypeSchema, EnumSchema, GeneratorOptions, ParsedSchema } from './types.js';

const DEFAULT_TYPE_MAP: Record<string, string> = {
  // Integers & Numbers
  int: 'number',
  int2: 'number',
  int4: 'number',
  int8: 'number',
  integer: 'number',
  smallint: 'number',
  bigint: 'number',
  serial: 'number',
  serial2: 'number',
  serial4: 'number',
  serial8: 'number',
  bigserial: 'number',
  smallserial: 'number',
  float4: 'number',
  float8: 'number',
  real: 'number',
  double: 'number',
  'double precision': 'number',
  numeric: 'number',
  decimal: 'number',

  // Strings / Text
  text: 'string',
  varchar: 'string',
  char: 'string',
  character: 'string',
  'character varying': 'string',
  uuid: 'string',
  bpchar: 'string',
  citext: 'string',

  // Boolean
  bool: 'boolean',
  boolean: 'boolean',

  // Date / Time
  date: 'Date',
  time: 'string',
  timetz: 'string',
  timestamp: 'Date',
  timestamptz: 'Date',
  'timestamp with time zone': 'Date',
  'timestamp without time zone': 'Date',
  interval: 'string',

  // JSON
  json: 'any',
  jsonb: 'any',

  // Misc
  bytea: 'Buffer',
  inet: 'string',
  cidr: 'string',
  macaddr: 'string',
  point: '{ x: number; y: number }',
};

function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, chr) => chr.toUpperCase())
    .replace(/^[a-z]/, (chr) => chr.toUpperCase());
}

export function generateTypeScript(
  schema: ParsedSchema,
  options: GeneratorOptions = {}
): string {
  const lines: string[] = [];
  const prefix = options.interfacePrefix || '';
  const suffix = options.interfaceSuffix || '';
  const customMap = options.customTypeMap || {};
  const typeMap = { ...DEFAULT_TYPE_MAP, ...customMap };

  if (options.generateHeaderBanner) {
    lines.push('/* Auto-generated by pgschema-to-ts. Do not edit directly. */');
    lines.push('');
  }

  // Track known enum names and composite type names for custom type mapping
  const knownEnums = new Set(schema.enums.map((e: EnumSchema) => e.name));
  const knownComposites = new Set((schema.compositeTypes || []).map((c: CompositeTypeSchema) => c.name));

  // 1. Generate Enum Types
  for (const enumDef of schema.enums) {
    const enumTypeName = `${prefix}${toPascalCase(enumDef.name)}${suffix}`;
    const valuesUnion = enumDef.values.map((v: string) => `'${v}'`).join(' | ');
    lines.push(`export type ${enumTypeName} = ${valuesUnion || 'string'};`);
    lines.push('');
  }

  // Helper function to resolve PG type to TS type
  function resolveTsType(pgType: string): string {
    const lower = pgType.toLowerCase();
    if (typeMap[lower]) {
      return typeMap[lower];
    }
    if (knownEnums.has(pgType) || knownComposites.has(pgType)) {
      return `${prefix}${toPascalCase(pgType)}${suffix}`;
    }
    return 'any';
  }

  // 2. Generate Composite Types Interfaces
  for (const comp of schema.compositeTypes || []) {
    const interfaceName = `${prefix}${toPascalCase(comp.name)}${suffix}`;
    lines.push(`export interface ${interfaceName} {`);
    for (const attr of comp.attributes) {
      let tsType = resolveTsType(attr.type);
      if (attr.isArray) {
        tsType = `${tsType}[]`;
      }
      lines.push(`  ${attr.name}: ${tsType} | null;`);
    }
    lines.push('}');
    lines.push('');
  }

  // 2. Generate Table Interfaces
  for (const table of schema.tables) {
    const interfaceName = `${prefix}${toPascalCase(table.name)}${suffix}`;

    // Base Interface
    lines.push(`export interface ${interfaceName} {`);
    for (const col of table.columns) {
      let tsType = resolveTsType(col.type);
      if (col.isArray) {
        tsType = `${tsType}[]`;
      }
      const optional = col.isNullable ? ' | null' : '';
      lines.push(`  ${col.name}: ${tsType}${optional};`);
    }
    lines.push('}');
    lines.push('');

    // Optional Insert / Update Helper Types
    if (options.generateInsertUpdateTypes) {
      const insertName = `${prefix}${toPascalCase(table.name)}Insert${suffix}`;
      const updateName = `${prefix}${toPascalCase(table.name)}Update${suffix}`;

      lines.push(`export interface ${insertName} {`);
      for (const col of table.columns) {
        let tsType = resolveTsType(col.type);
        if (col.isArray) {
          tsType = `${tsType}[]`;
        }
        const isOptional = col.isNullable || col.hasDefault;
        const optFlag = isOptional ? '?' : '';
        const nullability = col.isNullable ? ' | null' : '';
        lines.push(`  ${col.name}${optFlag}: ${tsType}${nullability};`);
      }
      lines.push('}');
      lines.push('');

      lines.push(`export type ${updateName} = Partial<${insertName}>;`);
      lines.push('');
    }
  }

  return lines.join('\n').trim() + '\n';
}
