import type { CompositeTypeSchema, DomainSchema, EnumSchema, GeneratorOptions, ParsedSchema, ViewSchema } from './types.js';

const DEFAULT_TYPE_MAP: Record<string, string> = {
  int: 'number',
  int2: 'number',
  int4: 'number',
  int8: 'number',
  integer: 'number',
  smallint: 'number',
  bigint: 'number',
  serial: 'number',
  serial2: 'number',
  serial4: 'number',
  serial8: 'number',
  bigserial: 'number',
  smallserial: 'number',
  float4: 'number',
  float8: 'number',
  real: 'number',
  double: 'number',
  'double precision': 'number',
  numeric: 'number',
  decimal: 'number',

  text: 'string',
  varchar: 'string',
  char: 'string',
  character: 'string',
  'character varying': 'string',
  uuid: 'string',
  bpchar: 'string',
  citext: 'string',

  bool: 'boolean',
  boolean: 'boolean',

  date: 'Date',
  time: 'string',
  timetz: 'string',
  timestamp: 'Date',
  timestamptz: 'Date',
  'timestamp with time zone': 'Date',
  'timestamp without time zone': 'Date',
  interval: 'string',

  json: 'any',
  jsonb: 'any',

  bytea: 'Buffer',
  inet: 'string',
  cidr: 'string',
  macaddr: 'string',
  point: '{ x: number; y: number }',
};

function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, chr) => chr.toUpperCase())
    .replace(/^[a-z]/, (chr) => chr.toUpperCase());
}

// `public` and absent schemas use just the object name; all others prefix with the schema in PascalCase.
function qualifiedTypeName(name: string, schema: string | undefined, prefix: string, suffix: string): string {
  const schemaPrefix = schema ? toPascalCase(schema) : '';
  return `${prefix}${schemaPrefix}${toPascalCase(name)}${suffix}`;
}

export function generateTypeScript(
  schema: ParsedSchema,
  options: GeneratorOptions = {}
): string {
  const lines: string[] = [];
  const prefix = options.interfacePrefix || '';
  const suffix = options.interfaceSuffix || '';
  const customMap = options.customTypeMap || {};
  const typeMap = { ...DEFAULT_TYPE_MAP, ...customMap };

  if (options.generateHeaderBanner) {
    lines.push('/* Auto-generated by pgschema-to-ts. Do not edit directly. */');
    lines.push('');
  }

  // Maps "schema.name" -> qualified TS type name for cross-reference resolution.
  const typeRegistry = new Map<string, string>();
  const register = (name: string, schemaName: string | undefined) => {
    const tsName = qualifiedTypeName(name, schemaName, prefix, suffix);
    typeRegistry.set(name, tsName);
    if (schemaName) typeRegistry.set(`${schemaName}.${name}`, tsName);
    return tsName;
  };

  for (const e of schema.enums) register(e.name, e.schema);
  for (const c of schema.compositeTypes || []) register(c.name, c.schema);
  for (const d of schema.domains || []) register(d.name, d.schema);

  function resolveTsType(pgType: string): string {
    const lower = pgType.toLowerCase();
    if (typeMap[lower]) return typeMap[lower];
    if (typeRegistry.has(pgType)) return typeRegistry.get(pgType)!;
    return 'any';
  }

  // 1. Enums
  for (const enumDef of schema.enums) {
    const typeName = qualifiedTypeName(enumDef.name, enumDef.schema, prefix, suffix);
    const valuesUnion = enumDef.values.map((v: string) => `'${v}'`).join(' | ');
    lines.push(`export type ${typeName} = ${valuesUnion || 'string'};`);
    lines.push('');
  }

  // 2. Domains
  for (const domain of schema.domains || []) {
    const typeName = qualifiedTypeName(domain.name, domain.schema, prefix, suffix);
    let tsType = resolveTsType(domain.baseType);
    if (domain.isArray) tsType = `${tsType}[]`;
    lines.push(`export type ${typeName} = ${tsType};`);
    lines.push('');
  }

  // 3. Composite Types
  for (const comp of schema.compositeTypes || []) {
    const interfaceName = qualifiedTypeName(comp.name, comp.schema, prefix, suffix);
    lines.push(`export interface ${interfaceName} {`);
    for (const attr of comp.attributes) {
      let tsType = resolveTsType(attr.type);
      if (attr.isArray) tsType = `${tsType}[]`;
      lines.push(`  ${attr.name}: ${tsType} | null;`);
    }
    lines.push('}');
    lines.push('');
  }

  // 4. Tables
  for (const table of schema.tables) {
    const interfaceName = qualifiedTypeName(table.name, table.schema, prefix, suffix);
    lines.push(`export interface ${interfaceName} {`);
    for (const col of table.columns) {
      let tsType = resolveTsType(col.type);
      if (col.isArray) tsType = `${tsType}[]`;
      const nullable = col.isNullable ? ' | null' : '';
      lines.push(`  ${col.name}: ${tsType}${nullable};`);
    }
    lines.push('}');
    lines.push('');

    if (options.generateInsertUpdateTypes) {
      const insertName = qualifiedTypeName(table.name, table.schema, prefix, `Insert${suffix}`);
      const updateName = qualifiedTypeName(table.name, table.schema, prefix, `Update${suffix}`);

      lines.push(`export interface ${insertName} {`);
      for (const col of table.columns) {
        let tsType = resolveTsType(col.type);
        if (col.isArray) tsType = `${tsType}[]`;
        const isOptional = col.isNullable || col.hasDefault;
        const optFlag = isOptional ? '?' : '';
        const nullable = col.isNullable ? ' | null' : '';
        lines.push(`  ${col.name}${optFlag}: ${tsType}${nullable};`);
      }
      lines.push('}');
      lines.push('');

      lines.push(`export type ${updateName} = Partial<${insertName}>;`);
      lines.push('');
    }
  }

  // 5. Views
  for (const view of schema.views || []) {
    const interfaceName = qualifiedTypeName(view.name, view.schema, prefix, suffix);
    lines.push(`export interface ${interfaceName} {`);
    for (const col of view.columns) {
      let tsType = resolveTsType(col.type);
      if (col.isArray) tsType = `${tsType}[]`;
      lines.push(`  ${col.name}: ${tsType} | null;`);
    }
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n').trim() + '\n';
}
